#!/bin/bash

source mysql-saudations/start.sh

source mysql-commands/load-config.sh

source mysql-prompts/get-operation.sh

echo $OPERATION

source mysql-prompts/get-service-number.sh

source mysql-prompts/get-database-name.sh

source mysql-prompts/get-table-prefix.sh

source mysql-commands-groups/$OPERATION$SERVICECOMPLEMENT.sh

source mysql-saudations/end.sh

